package.json
packages/next-app-with-apollo/package.json
packages/next-app-with-auth/package.json
packages/next-app-with-emotion/package.json
packages/next-app-with-helmet/package.json
packages/next-app-with-intl/package.json
packages/next-app-with-provider/package.json
packages/next-app-with-user/package.json
packages/next-config-with-workspaces/package.json
packages/next-document-with-emotion/package.json
packages/next-document-with-helmet/package.json

affects: @atlantis-lab/next-app-with-apollo, @atlantis-lab/next-app-with-auth,
@atlantis-lab/next-app-with-emotion, @atlantis-lab/next-app-with-helmet,
@atlantis-lab/next-app-with-intl, @atlantis-lab/next-app-with-provider,
@atlantis-lab/next-app-with-user, @monstrs/next-config-with-workspaces,
@atlantis-lab/next-document-with-emotion, @atlantis-lab/next-document-with-helmet

chore(packages): publishConfig update

---

packages/next-app-with-apollo/CHANGELOG.md
packages/next-app-with-apollo/package.json
packages/next-app-with-auth/CHANGELOG.md
packages/next-app-with-auth/package.json
packages/next-app-with-emotion/CHANGELOG.md
packages/next-app-with-emotion/package.json
packages/next-app-with-helmet/CHANGELOG.md
packages/next-app-with-helmet/package.json
packages/next-app-with-intl/CHANGELOG.md
packages/next-app-with-intl/package.json
packages/next-app-with-provider/CHANGELOG.md
packages/next-app-with-provider/package.json
packages/next-app-with-user/CHANGELOG.md
packages/next-app-with-user/package.json
packages/next-config-with-workspaces/CHANGELOG.md
packages/next-config-with-workspaces/package.json
packages/next-document-with-emotion/CHANGELOG.md
packages/next-document-with-emotion/package.json
packages/next-document-with-helmet/CHANGELOG.md
packages/next-document-with-helmet/package.json

- @atlantis-lab/next-app-with-apollo@0.0.2
- @atlantis-lab/next-app-with-auth@0.0.2
- @atlantis-lab/next-app-with-emotion@0.0.2
- @atlantis-lab/next-app-with-helmet@0.0.2
- @atlantis-lab/next-app-with-intl@0.0.2
- @atlantis-lab/next-app-with-provider@0.0.2
- @atlantis-lab/next-app-with-user@0.0.2
- @atlantis-lab/next-config-with-workspaces@0.0.2
- @atlantis-lab/next-document-with-emotion@0.0.2
- @atlantis-lab/next-document-with-helmet@0.0.2

chore(release): %s

---

package.json
packages/next-app-with-apollo/package.json
packages/next-app-with-auth/package.json
packages/next-app-with-emotion/package.json
packages/next-app-with-helmet/package.json
packages/next-app-with-intl/package.json
packages/next-app-with-provider/package.json
packages/next-app-with-user/package.json
packages/next-config-with-workspaces/package.json
packages/next-document-with-emotion/package.json
packages/next-document-with-helmet/package.json

affects: @atlantis-lab/next-app-with-apollo, @atlantis-lab/next-app-with-auth,
@atlantis-lab/next-app-with-emotion, @atlantis-lab/next-app-with-helmet,
@atlantis-lab/next-app-with-intl, @atlantis-lab/next-app-with-provider,
@atlantis-lab/next-app-with-user, @atlantis-lab/next-config-with-workspaces,
@atlantis-lab/next-document-with-emotion, @atlantis-lab/next-document-with-helmet

chore: update packages

---

packages/next-app-with-helmet/package.json
packages/next-app-with-intl/package.json
packages/next-app-with-provider/package.json

affects: @atlantis-lab/next-app-with-helmet, @atlantis-lab/next-app-with-intl,
@atlantis-lab/next-app-with-provider

fix(packages/package.json): src/index.ts -> dist/index.js

---

packages/next-app-with-auth/package.json
packages/next-app-with-auth/src/with-auth.provider.tsx
packages/next-app-with-intl/package.json
packages/next-app-with-intl/src/with-intl.provider.tsx
packages/next-app-with-user/package.json
packages/next-app-with-user/src/with-user.provider.tsx
yarn.lock

affects: @atlantis-lab/next-app-with-auth, @atlantis-lab/next-app-with-intl,
@atlantis-lab/next-app-with-user

refactor(packages): move from monstrs to atlantis

---

yarn.lock

Signed-off-by: Andrew Ghostuhin <me@torinasakura.name>

fix: add fresh yarn.lock

---

packages/next-document-with-helmet/src/with-helmet.provider.tsx
yarn.lock

affects: @atlantis-lab/next-document-with-helmet

refactor(helmet): add favicon links

---

packages/next-app-with-apollo/package.json
packages/next-app-with-apollo/src/init-apollo.ts
packages/next-app-with-apollo/src/with-apollo.provider.tsx
yarn.lock

affects: @atlantis-lab/next-app-with-apollo

refactor(next-app-with-apollo): change all apollo libs to @apollo/client

---

packages/next-app-with-apollo/__tests__/with-apollo.test.tsx
packages/next-app-with-auth/__tests__/with-auth.test.tsx
packages/next-app-with-auth/jest.config.ts
packages/next-app-with-auth/package.json

affects: @atlantis-lab/next-app-with-apollo, @atlantis-lab/next-app-with-auth
ISSUES CLOSED: #130

feat(next-app-with-auth): add test

---

packages/next-app-with-helmet/__tests__/with-helmet.test.tsx
packages/next-app-with-helmet/jest.config.ts
packages/next-app-with-helmet/package.json

affects: @atlantis-lab/next-app-with-helmet
ISSUES CLOSED: #137

feat(next-app-with-helmet): add test

---

packages/next-app-with-ismobile/__tests__/with-ismobile.test.tsx
packages/next-app-with-ismobile/jest.config.ts
packages/next-app-with-ismobile/package.json

affects: @atlantis-lab/next-app-with-ismobile
ISSUES CLOSED: #141

feat(next-app-with-ismobile): add test

---

packages/next-app-with-provider/__tests__/with-provider.test.tsx
packages/next-app-with-provider/jest.config.ts
packages/next-app-with-provider/package.json

affects: @atlantis-lab/next-app-with-provider
ISSUES CLOSED: #143

feat(next-app-with-provider): add test

---

packages/next-app-with-emotion/__tests__/with-emotion.test.tsx
packages/next-app-with-emotion/src/with-emotion.provider.tsx

affects: @atlantis-lab/next-app-with-emotion
ISSUES CLOSED: #145

fix(next-app-with-emotion): fix package's API & test

---

packages/next-app-with-user/__tests__/with-user.test.tsx
packages/next-app-with-user/jest.config.ts
packages/next-app-with-user/package.json

affects: @atlantis-lab/next-app-with-user
ISSUES CLOSED: #147

feat(next-app-with-user): add test

---

packages/next-document-with-emotion/__tests__/with-emotion.test.tsx
packages/next-document-with-emotion/jest.config.ts
packages/next-document-with-emotion/package.json

affects: @atlantis-lab/next-document-with-emotion
ISSUES CLOSED: #149

feat(next-document-with-emotion): add test

---

packages/next-document-with-helmet/__tests__/with-helmet.test.tsx
packages/next-document-with-helmet/jest.config.ts
packages/next-document-with-helmet/package.json

affects: @atlantis-lab/next-document-with-helmet
ISSUES CLOSED: #153

feat(next-document-with-helmet): add test

---

packages/next-config-with-workspaces/__tests__/stub.ts
packages/next-config-with-workspaces/__tests__/with-workspaces.test.tsx
packages/next-config-with-workspaces/jest.config.ts
packages/next-config-with-workspaces/package.json
packages/next-config-with-workspaces/src/with-workspaces.provider.tsx

affects: @atlantis-lab/next-config-with-workspaces
- Also added minor changes to `with-workspaces.provider.tsx` to set the environment for test
ISSUES CLOSED: #155

feat(next-config-with-workspaces): add test

---

package.json
packages/next-app-with-apollo/__tests__/with-apollo.test.tsx
packages/next-app-with-apollo/src/with-apollo.provider.tsx
packages/next-app-with-apollo/tsconfig.json
packages/next-app-with-auth/tsconfig.json
packages/next-app-with-emotion/tsconfig.json
packages/next-app-with-helmet/tsconfig.json
packages/next-app-with-intl/tsconfig.json
packages/next-app-with-ismobile/src/with-ismobile.provider.tsx
packages/next-app-with-ismobile/tsconfig.json
packages/next-app-with-provider/tsconfig.json
packages/next-app-with-user/tsconfig.json
packages/next-config-with-workspaces/__tests__/with-workspaces.test.tsx
packages/next-config-with-workspaces/src/with-workspaces.provider.tsx
packages/next-config-with-workspaces/tsconfig.json
packages/next-document-with-emotion/__tests__/with-emotion.test.tsx
packages/next-document-with-emotion/src/with-emotion.provider.tsx
packages/next-document-with-emotion/tsconfig.json
packages/next-document-with-helmet/__tests__/with-helmet.test.tsx
packages/next-document-with-helmet/tsconfig.json
tsconfig.json
yarn.lock

affects: @atlantis-lab/next-app-with-apollo, @atlantis-lab/next-app-with-auth,
@atlantis-lab/next-app-with-emotion, @atlantis-lab/next-app-with-helmet,
@atlantis-lab/next-app-with-intl, @atlantis-lab/next-app-with-ismobile,
@atlantis-lab/next-app-with-provider, @atlantis-lab/next-app-with-user,
@atlantis-lab/next-config-with-workspaces, @atlantis-lab/next-document-with-emotion,
@atlantis-lab/next-document-with-helmet
ISSUES CLOSED: #179

chore: move to actl

---

packages/next-app-with-apollo/package.json
packages/next-app-with-auth/package.json
packages/next-app-with-emotion/package.json
packages/next-app-with-helmet/package.json
packages/next-app-with-intl/package.json
packages/next-app-with-ismobile/package.json
packages/next-app-with-provider/package.json
packages/next-app-with-user/package.json
packages/next-config-with-workspaces/package.json
packages/next-document-with-emotion/package.json
packages/next-document-with-helmet/package.json
yarn.lock

affects: @atlantis-lab/next-app-with-auth, @atlantis-lab/next-app-with-intl,
@atlantis-lab/next-app-with-user
ISSUES CLOSED: #183

chore: update atlantis-lab/reactjs dependencies

---

packages/next-app-with-auth/src/with-auth.provider.tsx
packages/next-app-with-emotion/__tests__/with-emotion.test.tsx
packages/next-app-with-emotion/src/with-emotion.provider.tsx
packages/next-app-with-intl/src/with-intl.provider.tsx
packages/next-app-with-ismobile/src/with-ismobile.provider.tsx
packages/next-app-with-user/src/with-user.provider.tsx

affects: @atlantis-lab/next-app-with-auth, @atlantis-lab/next-app-with-emotion,
@atlantis-lab/next-app-with-intl, @atlantis-lab/next-app-with-ismobile,
@atlantis-lab/next-app-with-user
ISSUES CLOSED: #194

fix: satisfy typecheck on __NEXT_DATA__ property type reassign
